### ISSUE TITLE
Undefined array key "type"

### ISSUE THREAD

**Issue by thin-k-design** [lukaskleinschmidt/kirby-types#2]
When defining fields like this:
```
          fields:
            backgroundColor:
              extends: fields/colors
              label: Background Color
```
the plugin expects somewhere in the field definition a "type" key, but here only "extends" and "label" are present.

The output of the console is:
```
kirby-types v1.1.1 types:create
✓ added blueprints fields
Undefined array key "type"
```

**Comment by lukaskleinschmidt** [comment]
How does your `fields/colors.yml` file look like?

**Comment by thin-k-design** [comment]
```
type: select
mode: options
options:
  corporate: Dark Blue
  secondary: Slate Gray
  white: White
  offwhite: Off-White
  highlight: Harvest Gold
```

**Comment by lukaskleinschmidt** [comment]
That is really odd. Can't reproduce the behaviour in my test setup. Do you have any other plugins installed that might interfere?

**Comment by thin-k-design** [comment]
Sorry, I forgot to mention, I have installed the beta version of Kirby 4.
It is actually a pretty much clean installation with currently just one hook and one route in the config. So it must be an issue with Kirby 4. I can confirm, that it works in Kirby 3.

If I use
```
          fields:
            backgroundColor:
              extends: fields/colors
              **type: select**
              label: Background Color
```
it works.

**Comment by lukaskleinschmidt** [comment]
Which version of Kirby 4? I actually added a new [release](https://github.com/lukaskleinschmidt/kirby-types/releases/tag/2.0.0) for Kirby 4 a few minutes ago. But did not run into the issue you described with the older [`1.1.1`](https://github.com/lukaskleinschmidt/kirby-types/releases/tag/1.1.1) version either. At least with Kirby `4.0.0-beta.1`.

Could you please check if using the new release fixes the issue?

**Comment by thin-k-design** [comment]
Ok, so maybe Kirby 4 wasn't the cultprint, I am using the same version as you. Here is the full blueprint, it works as you stated for normal fields. I get the error when the extended field is in the layout settings:

```
fields:
  layout:
    type: layout
    layouts:
      - "1/1"
      - "1/2, 1/2"
      - "1/3, 2/3"
      - "2/3, 1/3"
    fieldsets:
      cards: blocks/cards
      buttons: blocks/buttons
      text: blocks/text
    settings:
      fields:
        backgroundColor:
          extends: fields/colors
          label: Background Color
```
